# -*- coding: utf-8 -*-
"""fixed_tensorflow_code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f69OyTjt589e4Rkfnhmd7hhXntkYZw7w
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.datasets import mnist

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Build model
model = Sequential([
    Flatten(input_shape=(28, 28)),  # Flatten 2D input
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile with correct loss function
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train
model.fit(x_train, y_train, epochs=5, validation_split=0.1)

# Evaluate
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_acc)

"""✅ Fixed Code

Added a Flatten() layer to convert the 2D image input into a 1D vector.

Replaced the loss function with sparse_categorical_crossentropy to match the label format.
"""